version: "3.1"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432
    volumes:
      - rvfc:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 60s

  server:
    build:
      context: ./russian-vocabulary-flash-cards-server
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - db

  client:
    build:
      context: ./russian-vocabulary-flash-cards-client
      dockerfile: Dockerfile
    ports:
      - 80:80
      - 443:443
    depends_on:
      - server

volumes:
  rvfc: