version: "3.1"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432
    volumes:
      - rvfc:/var/lib/postgresql/data

  server:
    build:
      context: ./russian-vocabulary-flash-cards-server
      dockerfile: Dockerfile
    ports:
      - 3000:3000

  client:
    build:
      context: ./russian-vocabulary-flash-cards-client
      dockerfile: Dockerfile
    ports:
      - 443:443

volumes:
  rvfc: